#!/bin/sh

LANG=$2

if [ "$LANG" != "" ]
  then LANG=$2
  else LANG='en'
fi

C=0
YEAR=$1

#echo $YEAR

geturl() {
BC='_BC'
case "$LANG" in
  es)   BC="_a._C." ;;
  it)   BC="_a.C." ;;
  en)   BC="_BC" ;;
  de)   BC='_v._Chr.';;
  fr)   BC='_av._J.-C.';;
  li)   BC='_v._Chr.';;
  pl)   BC='_p.n.e.';;
esac
	}

if [ "$1" -lt "$C" ]
then
  YEAR=$((-$1))   
  geturl
fi



JSON=$(wget 'https://'$LANG'.wikipedia.org/w/api.php?action=query&format=json&servedby=1&prop=extracts&list=&meta=&utf8=1&uselang='$LANG'&titles='$YEAR$BC -q -O -)

VAR=$(echo ${JSON} | jq -r '.query.pages[].extract')

touch /tmp/gethistory
echo "$VAR" > /tmp/gethistory
html2text -utf8 /tmp/gethistory | more
